name: CI – Hello World App

on:
  push:
    branches: [ master, main, develop ]
  workflow_dispatch:

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Docker network and MongoDB
        run: |
          docker network create se-methods || true
          docker run -d --name mongo-dbserver --network se-methods -p 27017:27017 mongo:7

      - name: Build with Maven
        run: mvn -B -DskipTests package

      - name: Build Docker image
        run: docker build -t se_methods .

      - name: Run image
        run: docker run -d --network se-methods --name devopscontainer se_methods

      - name: View logs
        run: docker logs --tail=200 devopscontainer || true
